# Use postgres/example user/password credentials
version: '3.1'

services:
  backend:
    build: ./server
    depends_on:
      - postgres
    volumes:
      - ./server:/usr/src/app/
    ports:
      - "8080:8080"

  react-app:
    build: ./pc-configurator
    ports:
      - 3000:80
    volumes:
      - /app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./db-create/create-db.sql:/docker-entrypoint-initdb.d/database-seed.sql

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    user: "${UID}:${GID}"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "16543:80"
    volumes:
      - /pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
