# Use postgres/example user/password credentials
version: '3.1'

services:
  react-app:
    build: ./pc-configurator
    ports:
      - 3000:80
    volumes:
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - /postgres-data:/var/lib/postgresql/data

